### ISSUE TITLE
Holiday allowance checkbox does nothing apparently

### ISSUE THREAD

**Issue by sadokx** [stevermeister/dutch-tax-income-calculator-old#55] opened 2017-05-22 02:06 UTC
No changes when I click the checkbox.

**Comment by mzaferyahsi** [comment] 2017-05-26 08:30
I created a merge request #56 about this. But it needs to be reviewed and merged.

**Comment by koraykupe** [comment] 2017-05-26 11:17
I think it is not a bug but the developer may have changed the behaviour regarding to an issue that was argued on #35 and #48 

It seems still confusing. In my opinion its reason may that some companies add the allowance to the net monthly wage but some of them pays it annually. So, if your company adds the allowance to your monthly wage, your calculation is correct. Otherwise you need to type your base salary (excl. holiday allowance) to find your monthly net. (_To find your base salary excl holiday allowance use the tip below_)

If the company said you that the allowance is included your salary but it will be paid based on the real accumulated earnings of the past year, type your gross to the input, enable "Year Gross Holiday Allowance" option and substract it your gross (manually) and type the difference to the input to calculate your monthly net again.

Am I wrong? I talked with two of my friends in Netherlands and I got this result.

**Comment by stevermeister** [comment] 2017-05-31 20:21
sorry guys, I was offline for sometime.
@sadokx true, thank you for the feedback!
@mzaferyahsi I made a commend about it.
@koraykupe it's so true. I looking for the way to make it simple and clear for everybody

**Comment by koraykupe** [comment] 2017-06-16 06:06
It shows € 3,604 as monthly net for 53000 gross and € 3,638 for 58000 gross.
(Holiday allowance included, Social security and 30% ruling selected)

There is only € 34 difference as net but € 5000 as gross.
May it be true? I think no.

**Comment by stevermeister** [comment] 2017-06-16 06:15
thank you for you feedback, 
but it is what it is: Payroll Tax is getting bigger in this case.
if you find exact mistake in calculation, please let me know.

**Comment by koraykupe** [comment] 2017-06-16 06:22
@stevermeister but the payroll tax difference between them is only € 339.

**Comment by stevermeister** [comment] 2017-06-16 06:41
yes, true. 
is it only for  `Holiday allowance` case?

**Comment by koraykupe** [comment] 2017-06-16 06:45
@stevermeister yes, but without `Holiday allowance` the difference is € 857 as well. Where did €5000 go?

**Comment by stevermeister** [comment] 2017-06-16 06:47
@eduardomourar may be you have an idea where we lost 5k?

**Comment by koraykupe** [comment] 2017-06-16 06:50
By the way, can real percentage be bigger than 30? It shows 32% for this situation: http://thetax.nl/?year=2017&startFrom=Year&salary=55000&allowance=1&socialSecurity=1&retired=0&ruling=1

**Comment by stevermeister** [comment] 2017-06-17 19:25
no, it can't be bigger than 30, it's one more bug :(

**Comment by stevermeister** [comment] 2017-06-17 19:32
also related to incorrect holiday allowance

**Comment by stevermeister** [comment] 2017-06-17 19:38
I disabled this option for now, while we don't figure out that would be the proper way to implement it also in UX not to may it so confusing

**Comment by eduardomourar** [comment] 2017-06-18 10:34
I did some checking to make sure that the calculation were alright:
![image](https://user-images.githubusercontent.com/16357187/27260005-c49281d8-5420-11e7-8be6-1d18b364b559.png)

So, the answer is yes, it is correct. Even though I am comparing 2015 and 2014, the same logic will apply but tax rates will be different. If you compare only annual amounts (year gross income vs. year net income), adding 5k (58k - 53k) to gross gives 3.5k (46k - 42.5k), which makes sense due to taxes.

**Comment by eduardomourar** [comment] 2017-06-18 10:57
Regarding the 32% real percentage, yes, it is wrong. That is because we were calculating the holiday allowance with normal rates, but it has a special rate for that. This was already fixed with the new version with angular 4.

![image](https://user-images.githubusercontent.com/16357187/27260173-975027d4-5425-11e7-9782-241b56925445.png)

**Comment by koraykupe** [comment] 2017-06-30 08:02
@eduardomourar My friend earns 55K gross yearly and gets 2835 (without 30% rule) and ~3400 (with the rule) in practice. It is less than your calculation. I don't know why. His company might pay holiday allowance yearly but he is not sure. He started in March this year. May it be related to it?

By the way,
How income taxes is calculated?
Let's assume that taxable income is 37000
2017 Total rate is 36.55% up to € 19,982
and 40.80% for € 19,982 to € 67,072
Is the tax amount 37000 * 40.80 = **15.096** or (19982*36.55) + (37000-19982)*40.80 = 7303 + 6943 = **14.246**?

And how is personal tax credit and Labour tax credit calculated? Does having a child effect the tax credit amount?

**Comment by eduardomourar** [comment] 2017-06-30 21:58
@koraykupe, first of all, let me be clear that I am not a Dutch tax expert. That being said, there are other tax benefits that this tool doesn't consider like rent benefit, child benefit (that you mentioned and it does effect the overall tax credit, yes) and health care benefit, which might apply to your friend.
Just so you know, I also started to work in the Netherlands March 20th this year, and when I compare the monthly gross amount on my payslip, the calculator has €1 less (without 30% ruling) and €2 less (with ruling). So when you have a case like this, that you need to calculate taxes partially for a year and also for a month, getting the precise amount can be really hard and I guess that is why you see a difference. Also, keep in mind that is quite common to receive the full (or proportional in my case because I only worked 53 out of 260 business days) holiday allowance in May, or sometimes June.

Regarding your other question, if you are talking about taxes on a payslip level, your calculation is correct for the tax amount (payroll + social security tax) ~€14.247. To calculate tax credit I would suggest you look into the code and links [here](https://github.com/eduardomourar/dutch-tax-income-calculator2/blob/master/src/app/calculate.service.ts), but basically general credit €1.439, which is €2.254 - 4,787% x (37.000 - 19.982), and labour credit €3.058, which is €3.223 - 3,6% x (37.000 - 32.444).

**Closed as completed** 2020-01-07 09:49 UTC
